### ISSUE TITLE
Add instructions on importing SCATS data into mongo

### ISSUE THREAD

**Issue by rhyolight** [JonnoFTW/htm-models-adelaide#1]
README says: "1. Import the SCATS data into your mongo instance" but there are no instructions on how to do this. I have three data files: `crashes.json`, `locations.json`, and `readings.json`. I assume these need to go into mongo. Can you tell me how to do this? I'm a mongo newbie.

**Comment by JonnoFTW** [comment]
Make sure mongo is running somewhere and you have user access. I have also updated the readme with these instructions. Make sure you've got mongo installed and in your path and run:

```
mongoimport --db htm_adelaide --collection readings --file readings.json
mongoimport --db htm_adelaide --collection crashes --file crashes.json --numInsertionWorkers 3
mongoimport --db htm_adelaide --collection locations --file locations.json
```

Then open the mongo client, `mongo` and create the indexes using:

```
db.crashes.createIndex({datetime: 1})
db.crashes.createIndex({loc: "2dsphere"})
db.locations.createIndex({intersection_number: 1})
db.locations.createIndex({loc: "2dsphere"})
db.readings.createIndex({datetime: 1})
db.readings.createIndex({site_no: 1})
```

From there you should be able to run the anomaly detection script.

**Comment by rhyolight** [comment]
I also needed to add `--host=127.0.0.1` to the `mongoimport` commands.

**Comment by rhyolight** [comment]
Ha, now I see the note you made about that :)
