### ISSUE TITLE
Using index.py for swarming vs model run

### ISSUE THREAD

**Issue by rhyolight** [JonnoFTW/htm-models-adelaide#2]
README says:

```
4. Run the swarm using `index.py` to generate the model parameters.
5. Run the model using `index.py` and evaluate anomaly results
```

How do I specify to the `index.py` script to either swarm or run the model? I don't see any options for this.

**Comment by JonnoFTW** [comment]
You don't need to worry about using the swarm any more. The engine uses the params from the model params now. After you've imported the data, you can just run the anomaly detection using

```
./index.py --intersection 3084 --write-anomaly --multi-model
```

I should probably have picked a better name than `index.py`... I'll fix the readme as well.
